version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-nginx-app
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginc/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend