version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    networks:
      - default
    restart: always
    
networks:
  default:
    driver: bridge
