version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" # Map port 8080 in the container to port 80 on the host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0  # Ensure the server listens on all network interfaces
    networks:
      - default

networks:
  default:
    driver: bridge
